services:
  postgres:
    image: postgres:15
    container_name: taller_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: taller_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: taller_backend
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    command: npm run dev

volumes:
  postgres_data:
